version: '3'

services:
  postgres:
    image: "postgres:16.0"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
  redis-stack:
    image: "redis/redis-stack:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
      - "8001:8001"


